using UnityEngine;
using System.Collections;
using System.Collections.Generic;
using System;

//Class generated by http://json2csharp.com/ for parsing the json string we got from the svpra server.
/// <summary>
/// A occurence of attraction
/// </summary>
[Serializable]
public class Attraction
{
	/// <summary>
	/// Id of the attraction
	/// </summary>
	public string Id { get; set; }
	/// <summary>
	/// Name of the attraction
	/// </summary>
	public string name { get; set; }
	/// <summary>
	/// Its description
	/// </summary>
	public string description { get; set; }
	/// <summary>
	/// Modification date
	/// </summary>
	public string lastModificationDate { get; set; }
	/// <summary>
	/// Creation date
	/// </summary>
	public string addDate { get; set; }
	/// <summary>
	/// List of object in that attraction
	/// </summary>
	public Dictionary<string, Element> elements { get; set; }

	public Element ContainFileName(string fileName)
	{
		foreach (Element ele in elements.Values)
		{
			if (fileName == ele.fileName)
			{
				return ele;
			}
		}
		return null;
	}

	public static Dictionary<string, Attraction> Parse(string json)
	{
		Dictionary<string, Attraction> attractions = new Dictionary<string, Attraction>();

		List<System.Object> listAttractions = Json.Deserialize(json) as List<System.Object>;
		foreach (System.Object objAttraction in listAttractions)
		{
			Dictionary<string, System.Object> dicAttraction = objAttraction as Dictionary<string, System.Object>;
			Attraction attraction = new Attraction();

			attraction.Id = dicAttraction["id"] as string;
			attraction.name = dicAttraction["nom"] as string;
			attraction.description = dicAttraction["description"] as string;
			attraction.addDate = dicAttraction["dateAjoute"] as string;
			attraction.lastModificationDate = dicAttraction["dateModifie"] as string;
			attraction.elements = new Dictionary<string, Element>();

			List<System.Object> listElements = dicAttraction["elements"] as List<System.Object>;
			foreach (System.Object objElement in listElements)
			{
				Dictionary<string, System.Object> dicElement = objElement as Dictionary<string, System.Object>;
				Element element = new Element();

				element.id = dicElement["id"] as string;
				element.title = dicElement["titre"] as string;
				element.description = dicElement["description"] as string;
				element.type = dicElement["type"] as string;
				element.latitude = dicElement["latitude"] as string;
				element.longitude = dicElement["longitude"] as string;
				element.elevation = dicElement["elevation"] as string;
				element.orientation = dicElement["orientation"] as string;
				element.transparency = dicElement["transparence"] as string;
				element.ratio = dicElement["ratio"] as string;
				element.fileName = dicElement["nomFichier"] as string;
				element.addDate = dicElement["eDateAjoute"] as string;
				element.lastModificationDate = dicElement["eDateModifie"] as string;

				attraction.elements.Add(element.id, element);
			}

			attractions.Add(attraction.Id, attraction);
		}

		return attractions;
	}
}

/// <summary>
/// A geo object
/// </summary>
[Serializable]
public class Element
{
	/// <summary>
	/// Id of the object
	/// </summary>
	public string id { get; set; }
	/// <summary>
	/// Its title
	/// </summary>
	public string title { get; set; }
	/// <summary>
	/// Its description
	/// </summary>
	public string description { get; set; }
	/// <summary>
	/// Its latitude
	/// </summary>
	public string longitude { get; set; }
	/// <summary>
	/// Its latitude
	/// </summary>
	public string latitude { get; set; }
	/// <summary>
	/// Its heading
	/// </summary>
	public string orientation { get; set; }
	/// <summary>
	/// File name associed with the object
	/// </summary>
	public string fileName { get; set; }
	/// <summary>
	/// Modification date
	/// </summary>
	public string lastModificationDate { get; set; }
	/// <summary>
	/// Creation date
	/// </summary>
	public string addDate { get; set; }
	/// <summary>
	/// Value of alpha channel
	/// </summary>
	public string transparency { get; set; }
	/// <summary>
	/// Scale of the object
	/// </summary>
	public string ratio { get; set; }
	/// <summary>
	/// Its altitude
	/// </summary>
	public string elevation { get; set; }
	/// <summary>
	/// Type of the object.
	/// </summary>
	public string type { get; set; }
}

